# config.ini
[copernicus]

client_id = sh-cceb593a-56cc-43b2-94f1-6aa15994db47
client_secret = Tcribdna8FVGwoVAP4c3HRhetbAoRjNX
username = yu.ye@um.es
password = $LK4*7}^dq;s'N7
;client_id = sh-81e8e5d1-4957-42d1-adc9-d5cc230bee40
;client_secret = JYNzWkGmkjvjhyKLVhl7IhYk23KFdSlE
;username = antonio.martinezi@um.es
;password = KVS*'Q)y6Wkis"a
