# Graph configuration parameters

# Input / Output
# inputFile=/home/antonio/Documentos/CienciasMarinas/Nitrates/Code/Copernicus/SAFE_downloads/S2A_MSIL1C_20180131T105251_N0500_R051_T30SXG_20230916T185601.SAFE.zip
# outputFile=/home/antonio/Descargas/Subset_S2A_MSIL1C_20180131T105251_resampled.tif
inputFile=
outputFile=

#BEAM-DIMAP o GeoTIFF
outputFormat=GeoTIFF 

# Resample
resampleResolution=10

# Spatial Subset
geoRegion=POLYGON((-0.867 37.62, -0.867 37.82, -0.7 37.82, -0.7 37.62, -0.867 37.62))

# C2RCC.msi
# salinity=42
# temperature=20
# # netSet : C2X-Nets | C2X-COMPLEX-Nets
# # netSet=C2X-Nets
# outputRtoa=false
# outputAcReflectance=true
# outputRhown=true

# Band Subset
bandSubset=B1,B2,B3,B4,B5,B6,B7,B8A


